id: 20bb3993-d04a-406a-8ded-292039c675b9
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: Google Drive Playbook Automation
description: Automate Google Drive alert remediation with our solution that revokes
  over-access permissions and shares file details and links with end-users via Slack.
  Reco workflow seamlessly integrates with Palo Alto Networks' Demisto platform to
  resolve the alert and streamline your organization's security operations. By automating
  remediation, you can ensure that sensitive data is protected and that end-users
  are promptly notified of any changes to their file access. With our solution, you
  can close alerts in Demisto and improve your organization's security posture with
  minimal effort.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b65b880c-90fa-48db-8aa9-e3ba48512bf5
    type: start
    task:
      id: b65b880c-90fa-48db-8aa9-e3ba48512bf5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "91"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "63":
    id: "63"
    taskid: b2cb0461-6dfd-4f56-84d3-4915d727bfda
    type: regular
    task:
      id: b2cb0461-6dfd-4f56-84d3-4915d727bfda
      version: -1
      name: Get Slack User
      description: Get details about a specified user.
      script: SlackV3|||slack-get-user-details
      type: regular
      iscommand: true
      brand: SlackV3
    nexttasks:
      '#none#':
      - "64"
    scriptarguments:
      user:
        simple: ${incident.labels.asset_owner}
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "64":
    id: "64"
    taskid: 9784ec91-6ce9-4a87-8f12-1ed09336693b
    type: condition
    task:
      id: 9784ec91-6ce9-4a87-8f12-1ed09336693b
      version: -1
      name: Is a Slack user?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "86"
      "yes":
      - "85"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Slack.User.ID
            iscontext: true
          right:
            value: {}
    - label: "no"
      condition:
      - - operator: isNotExists
          left:
            value:
              simple: Slack.User.ID
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "85":
    id: "85"
    taskid: e5af6cea-ac64-4a39-8ea4-456c24d4e963
    type: regular
    task:
      id: e5af6cea-ac64-4a39-8ea4-456c24d4e963
      version: -1
      name: Notify Asset Owner
      description: Sends a message to a user, group, or channel.
      script: SlackV3|||send-notification
      type: regular
      iscommand: true
      brand: SlackV3
    nexttasks:
      '#none#':
      - "90"
    scriptarguments:
      blocks:
        simple: "[\n\t\t{\n\t\t\t\"type\": \"section\",\n\t\t\t\"text\": {\n\t\t\t\t\"type\":
          \"mrkdwn\",\n\t\t\t\t\"text\": \"Hello ${incident.labels.asset_owner},\\n\\nWe
          have identified sensitive file(s) belonging to you that are publicly exposed.\"\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"type\":
          \"divider\"\n\t\t},\n\t\t{\n\t\t\t\"type\": \"section\",\n\t\t\t\"text\":
          {\n\t\t\t\t\"type\": \"mrkdwn\",\n\t\t\t\t\"text\": \"*Sensitive File(s)
          with revoked public permissions:*\\n ${finalstring}\"\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"type\":
          \"divider\"\n\t\t},\n\t\t{\n\t\t\t\"type\": \"section\",\n\t\t\t\"text\":
          {\n\t\t\t\t\"type\": \"mrkdwn\",\n\t\t\t\t\"text\": \"Selecting \\\"Anyone
          with this link\\\" widely exposes the file to anyone who has the link. Therefore,
          if the resource should not be shared *publicly*, you are requested to limit
          the access permissions to specified identities or restricted users only.\"\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"type\":
          \"section\",\n\t\t\t\"fields\": [\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"mrkdwn\",\n\t\t\t\t\t\"text\":
          \"For more information please contact security team\"\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t]"
      to:
        simple: ${incident.labels.asset_owner}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "86":
    id: "86"
    taskid: 57662f73-9fa2-4d97-883b-edee093c0e7a
    type: regular
    task:
      id: 57662f73-9fa2-4d97-883b-edee093c0e7a
      version: -1
      name: Notify SecOps
      description: Sends a message to a user, group, or channel.
      script: SlackV3|||send-notification
      type: regular
      iscommand: true
      brand: SlackV3
    nexttasks:
      '#none#':
      - "90"
    scriptarguments:
      blocks:
        simple: "[\n\t\t{\n\t\t\t\"type\": \"section\",\n\t\t\t\"text\": {\n\t\t\t\t\"type\":
          \"mrkdwn\",\n\t\t\t\t\"text\": \"Reco finding remediated by PAWN XSOAR.\"\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"type\":
          \"section\",\n\t\t\t\"fields\": [\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"mrkdwn\",\n\t\t\t\t\t\"text\":
          \"**Sensitive File(s) with revoked public permissions:*\\n ${finalstring}\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\":
          \"mrkdwn\",\n\t\t\t\t\t\"text\": \"*DM to the user for more information:*\\n${incident.labels.asset_owner}\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\":
          \"mrkdwn\",\n\t\t\t\t\t\"text\": \"*Link to Finding:*\\nhttps://[customer].reco.ai/inicdent/${incident.dbotMirrorId}\"\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t]"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "87":
    id: "87"
    taskid: 9c5dcf14-5cc0-4150-8ac4-3ada81e0ea66
    type: condition
    task:
      id: 9c5dcf14-5cc0-4150-8ac4-3ada81e0ea66
      version: -1
      name: Check is message exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "90"
      "yes":
      - "63"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ${finalstring}
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "90":
    id: "90"
    taskid: bae95b80-d757-4226-81c0-b1ece7068c79
    type: regular
    task:
      id: bae95b80-d757-4226-81c0-b1ece7068c79
      version: -1
      name: Close incident
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      closeNotes:
        simple: Permissions_automatically_removed
      closeReason:
        simple: Resolved
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "91":
    id: "91"
    taskid: c83193d8-2aaf-4a10-8661-a2a6f16fbe8d
    type: playbook
    task:
      id: c83193d8-2aaf-4a10-8661-a2a6f16fbe8d
      version: -1
      name: Reco-Google-Drive-Revoke-Permissions
      playbookName: Reco-Google-Drive-Revoke-Permissions
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "87"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "87_90_#default#": 0.35
    },
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: 3f37dfe4-4eff-43bd-8008-354a06b5de80
