id: 20bb3993-d04a-406a-8ded-292039c675b9
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: Google Drive Playbook Automation
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: eeb0cb12-2235-40c9-8cc1-681f62ceb52a
    type: start
    task:
      id: eeb0cb12-2235-40c9-8cc1-681f62ceb52a
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "84"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "63":
    id: "63"
    taskid: 25d93753-e6af-4d3c-87c0-428cf18f93f6
    type: regular
    task:
      id: 25d93753-e6af-4d3c-87c0-428cf18f93f6
      version: -1
      name: Get Slack User
      description: Get details about a specified user.
      script: SlackV3|||slack-get-user-details
      type: regular
      iscommand: true
      brand: SlackV3
    nexttasks:
      '#none#':
      - "64"
    scriptarguments:
      user:
        simple: ${incident.labels.asset_owner}
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "64":
    id: "64"
    taskid: 991b4d58-5afe-4f63-80dc-875da5cb0be8
    type: condition
    task:
      id: 991b4d58-5afe-4f63-80dc-875da5cb0be8
      version: -1
      name: Is a Slack user?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "86"
      "yes":
      - "85"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Slack.User.ID
            iscontext: true
          right:
            value: {}
    - label: "no"
      condition:
      - - operator: isNotExists
          left:
            value:
              simple: Slack.User.ID
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "84":
    id: "84"
    taskid: 2eb33149-d328-43e2-8f16-2f91e6792212
    type: playbook
    task:
      id: 2eb33149-d328-43e2-8f16-2f91e6792212
      version: -1
      name: Reco-Revoke-Assets
      playbookName: Reco-Revoke-Assets
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "87"
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "85":
    id: "85"
    taskid: 512ced1f-f388-4dfe-8c78-d8e2664e9187
    type: regular
    task:
      id: 512ced1f-f388-4dfe-8c78-d8e2664e9187
      version: -1
      name: Notify Asset Owner
      description: Sends a message to a user, group, or channel.
      script: SlackV3|||send-notification
      type: regular
      iscommand: true
      brand: SlackV3
    nexttasks:
      '#none#':
      - "90"
    scriptarguments:
      blocks:
        simple: "[\n\t\t{\n\t\t\t\"type\": \"section\",\n\t\t\t\"text\": {\n\t\t\t\t\"type\":
          \"mrkdwn\",\n\t\t\t\t\"text\": \"Hello ${incident.labels.asset_owner},\\n\\nWe
          have identified sensitive file(s) belonging to you that are publicly exposed.\"\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"type\":
          \"divider\"\n\t\t},\n\t\t{\n\t\t\t\"type\": \"section\",\n\t\t\t\"text\":
          {\n\t\t\t\t\"type\": \"mrkdwn\",\n\t\t\t\t\"text\": \"*Sensitive File(s)
          with revoked public permissions:*\\n ${finalstring}\"\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"type\":
          \"divider\"\n\t\t},\n\t\t{\n\t\t\t\"type\": \"section\",\n\t\t\t\"text\":
          {\n\t\t\t\t\"type\": \"mrkdwn\",\n\t\t\t\t\"text\": \"Selecting \\\"Anyone
          with this link\\\" widely exposes the file to anyone who has the link. Therefore,
          if the resource should not be shared *publicly*, you are requested to limit
          the access permissions to specified identities or restricted users only.\"\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"type\":
          \"section\",\n\t\t\t\"fields\": [\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"mrkdwn\",\n\t\t\t\t\t\"text\":
          \"For more information please contact security team\"\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t]"
      to:
        simple: ${incident.labels.asset_owner}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "86":
    id: "86"
    taskid: a6124baf-88aa-4a12-8fe8-b1122307a30e
    type: regular
    task:
      id: a6124baf-88aa-4a12-8fe8-b1122307a30e
      version: -1
      name: Notify SecOps
      description: Sends a message to a user, group, or channel.
      script: SlackV3|||send-notification
      type: regular
      iscommand: true
      brand: SlackV3
    nexttasks:
      '#none#':
      - "90"
    scriptarguments:
      blocks:
        simple: "[\n\t\t{\n\t\t\t\"type\": \"section\",\n\t\t\t\"text\": {\n\t\t\t\t\"type\":
          \"mrkdwn\",\n\t\t\t\t\"text\": \"Reco finding remediated by PAWN XSOAR.\"\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"type\":
          \"section\",\n\t\t\t\"fields\": [\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"mrkdwn\",\n\t\t\t\t\t\"text\":
          \"**Sensitive File(s) with revoked public permissions:*\\n ${finalstring}\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\":
          \"mrkdwn\",\n\t\t\t\t\t\"text\": \"*DM to the user for more information:*\\n${incident.labels.asset_owner}\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\":
          \"mrkdwn\",\n\t\t\t\t\t\"text\": \"*Link to Finding:*\\nhttps://[customer].reco.ai/inicdent/${incident.dbotMirrorId}\"\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t]"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "87":
    id: "87"
    taskid: de3874bf-d10c-4142-89bf-a93e4a6fcfd1
    type: condition
    task:
      id: de3874bf-d10c-4142-89bf-a93e4a6fcfd1
      version: -1
      name: Check is message exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "90"
      "yes":
      - "63"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ${finalstring}
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "90":
    id: "90"
    taskid: 5fe8623a-10e8-4dd5-8619-d34bd88a847a
    type: regular
    task:
      id: 5fe8623a-10e8-4dd5-8619-d34bd88a847a
      version: -1
      name: Close incident
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      closeNotes:
        simple: Permissions_automatically_removed
      closeReason:
        simple: Resolved
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "87_90_#default#": 0.35
    },
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: 3f37dfe4-4eff-43bd-8008-354a06b5de80
